### ISSUE TITLE
Inference on Point Clouds

### ISSUE THREAD

**Issue by satyajitghana** [cvg/DeepLSD#9]
Would there be a possibility to make this work on point cloud ? with inputs as x, y, z or even retrain it so that it works on point clouds to detect lines on it?

I tried to rasterize the point cloud data and try to detect lines, but that doesn't work that well

![image](https://user-images.githubusercontent.com/8092481/212018719-0d0df4b5-3e4b-43b5-82a4-e644a6cd6e28.png)

**Comment by rpautrat** [comment]
You might need to fine-tune it on point cloud data to make it really work, because the current data is probably to different from what it was trained on. But this might be possible with some effort, yes.

Otherwise, fitting lines to your point cloud by casting this as a multi-model fitting should also work.

**Comment by satyajitghana** [comment]
thanks :)
